language: node_js

node_js:
  - 'node'

install:
  - cd fe
  - npm install
  - npm install -g travis-ci-cloudfront-invalidation

env:
  - REACT_APP_ENV_TYPE=$(if ["$TRAVIS_TAG" != ""]; then echo "prod"; else echo "dev"; fi)

before_deploy:
  - REACT_APP_ENV=prod
  - CI=false
  - npm run build;

deploy:
  - provider: s3
    access_key_id: $aws_access_key_id
    secret_access_key: $aws_secret_access_key
    bucket: corona-travis-test
    skip_cleanup: true
    region: us-west-2
    acl: public_read
    local_dir: build
  - provider: s3
    access_key_id: $aws_access_key_id
    secret_access_key: $aws_secret_access_key
    bucket: corona-travis-test
    skip_cleanup: true
    region: us-west-2
    acl: public_read
    local_dir: build
    on:
      tags: true
      
notifications:
  email: false
